# Generated by Django 3.1 on 2021-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Description', models.CharField(max_length=512)),
                ('Image', models.ImageField(upload_to='static/prods/')),
            ],
        ),
    ]
