# Generated by Django 3.1 on 2021-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '2 - Product', 'verbose_name_plural': '2 - Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(max_length=512),
        ),
    ]
