# Generated by Django 3.1 on 2021-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210316_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(max_length=800),
        ),
    ]
