# Generated by Django 3.1 on 2021-03-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210316_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(height_field=432, upload_to='static/prods/', width_field=768),
        ),
    ]
