# Generated by Django 3.1 on 2021-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210316_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(height_field='432', upload_to='static/prods/', width_field='768'),
        ),
    ]
