# Generated by Django 3.1 on 2021-03-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210316_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(height_field='432px', upload_to='static/prods/', width_field='768px'),
        ),
    ]
