# Generated by Django 3.1 on 2021-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210316_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to='static/prods/'),
        ),
    ]
