# Generated by Django 3.1 on 2021-03-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': '3 - Quote', 'verbose_name_plural': '3 - Quotes'},
        ),
    ]
