# Generated by Django 3.1 on 2021-03-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210316_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.FileField(upload_to='static/prods/'),
        ),
    ]
